name: anki_spanish_sync
description: Spanish vocabulary highlighter for language learning
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  file_picker: ^8.1.2
  archive: ^3.6.1
  shared_preferences: ^2.3.2
  video_player: ^2.9.2
  video_player_web: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
